name: Super-Linter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment Stage'
        required: true
        default: 'prod'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          echo "Stage: ${{ matrix.stage }}"
        env:
          STAGE: ${{ matrix.stage }}

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Manual Approval
        if: matrix.stage == 'prod'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Deployment Approval',
              head: context.sha,
              base: 'prod'
            });
            console.log('Pull request created:', response.data.html_url);
