name: Super-Linter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment Stage'
        required: true
        default: 'prod'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [dev, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure environment
        run: |
          echo "Stage: ${{ matrix.stage }}"
        env:
          STAGE: ${{ matrix.stage }}

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Manual Approval
        if: matrix.stage == 'prod'
        run: |
          echo "Create Deployment Approval Pull Request"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          RESPONSE=$(curl --request POST \
            --url https://api.github.com/repos/$GITHUB_REPOSITORY/pulls \
            --header 'Authorization: Bearer $TOKEN' \
            --header 'Content-Type: application/json' \
            --data '{
              "title": "Deployment Approval",
              "head": "$GITHUB_SHA",
              "base": "prod"
            }')
          PR_URL=$(echo $RESPONSE | jq -r '.html_url')
          echo "Pull request created: $PR_URL"
